### ISSUE TITLE
filters.python missing from install?

### ISSUE THREAD

**Issue by kvenkman** [PDAL/python#179]
Hi, I tried installing Python support for PDAL in a new environment yet seems to be missing from the install. Could you help me debug this?

Code to recreate issue:

```
conda create -n 'pdal-test'
conda activate pdal-test
conda install python-pdal
pdal --drivers | grep python
```

The version of pdal that gets installed is 2.8.0, python-pdal v3.4.5. Restricting the installed numpy version to be <2 did not help.

**Comment by hobu** [comment]
assuming you are on windows, I think this is still an issue https://github.com/conda-forge/python-pdal-feedstock/issues/124

**Comment by kvenkman** [comment]
Hmm, I'm on a linux system - would it still be a pathing issue?

**Comment by kvenkman** [comment]
FWIW, installing v3.3.0 seems to solve the issue. PDAL v2.7.1 gets installed in this case.

**Comment by hobu** [comment]
yeah the older python-pdal did its setting of `PDAL_DRIVER_PATH` very differently than happens now. It "worked" in the wrong way. I think I know what to do to fix this, and I just need the cycles to address it. 

I'm also working on some other python-pdal tickets, so hopefully it'll all come together at once.

**Comment by kvenkman** [comment]
If you could point me to where the issue is, I'd be happy to help/contribute if needed!

**Comment by hobu** [comment]
It's some combo of where https://github.com/conda-forge/python-pdal-feedstock/blob/main/recipe/build.sh#L38 happens mixed with the [activation script(s)](https://github.com/conda-forge/python-pdal-feedstock/tree/main/recipe/scripts) that use it. We need to add another directory because `filters.python` and `readers.numpy` are installed into site-packages, not the `$CONDA_PREFIX/bin` path. In short, `PDAL_DRIVER_PATH` needs to now reference both places.

**Comment by kvenkman** [comment]
Ok, I'll try to take a crack at it today.

**Comment by hobu** [comment]
https://github.com/conda-forge/python-pdal-feedstock/pull/129 should fix this. Please reopen over there if not the case.
